version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: "adm"
      RABBITMQ_DEFAULT_PASS: "adm"
    ports:
      - '5672:5672'
      - '15672:15672'